[package]
name = "terminal-io"
version = "0.3.1-alpha.0"
description = "Utilities for reading and writing on terminals"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["cli", "io"]
categories = ["command-line-interface"]
repository = "https://github.com/sunfishcode/terminal-io"
readme = "README.md"

[build-dependencies]
rustc_version = "0.3.3"

[dependencies]
unsafe-io = "0.6.0"
duplex = "0.3.0"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.82"
posish = "0.6.0"
terminfo = "0.7.3"

[target.'cfg(windows)'.dependencies]
atty = "0.2.14"

[badges]
maintenance = { status = "actively-developed" }
