[package]
name = "terminal-io"
version = "0.10.2"
description = "Utilities for reading and writing on terminals"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["cli", "io"]
categories = ["command-line-interface"]
repository = "https://github.com/sunfishcode/terminal-io"
exclude = ["/.github"]

[dependencies]
io-extras = "0.12.0"
duplex = "0.10.0"
io-lifetimes = { version = "0.4.0", default-features = false }

[target.'cfg(not(windows))'.dependencies]
rustix = "0.32.0"
terminfo = "0.7.3"

[target.'cfg(windows)'.dependencies]
atty = "0.2.14"

[badges]
maintenance = { status = "actively-developed" }
